version: '3.9'

services:
        app:
                image: 'authservice-app'
                container_name: 'authservice-app-container'
                ports:
                        - "8081:8081"
                depends_on:
                        - postgres
                environment:
                        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authservice
                        SPRING_DATASOURCE_USERNAME: admin
                        SPRING_DATASOURCE_PASSWORD: /run/secrets/db_password
                secrets:
                        - db_password


        postgres:
                image: 'postgres:16.8-alpine'
                container_name: 'mi-postgres-container'
                ports:
                        - "5434:5432"
                environment:
                        POSTGRES_USER: admin
                        POSTGRES_PASSWORD: /run/secrets/db_password
                        POSTGRES_DB: authservice
                secrets:
                        - db_password

secrets:
        db_password:
                file: db_password.txt