spring:
    application:
        name: authservice
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            data-source-properties:
                tcpKeepAlive: true
        password:
            file: ${SPRING_DATASOURCE_PASSWORD_FILE}
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
jwt:
    issuer: ${JWT_ISSUER:http://localhost:8081}
    audience: ${JWT_AUDIENCE:authservice}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
    private:
        key:
            file: ${JWT_PRIVATE_KEY_FILE}
    public:
        key: classpath:publickey.pem
oauth2-client:
    client-id: ${OAUTH2_CLIENT_ID:authservice-client}
    client-secret: ${OAUTH2_CLIENT_SECRET:dev-client-secret}
    redirect-uris: ${OAUTH2_REDIRECT_URIS:http://127.0.0.1:8081/login/oauth2/code/authservice,https://oauth.pstmn.io/v1/callback}
    refresh-token-ttl: ${OAUTH2_REFRESH_TOKEN_TTL:24h}
server:
    port: 8081
springdoc:
    swagger-ui:
        tryItOutEnabled: true