name: Build and Push to Docker Hub and Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
      
      - name: SSH and Deploy on EC2
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
            chmod 600 ec2_key.pem
            ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker-compose -f ~/docker-compose.yml down || true
            docker-compose -f ~/docker-compose.yml up -d
            EOF
